// Computer Architecture CO2070 - Lab 04_5
// Design: 8-bit ALU - Extended ISA
// Team  : 06
// Members : E/22/014, E/22/035

// Operations (SELECT encoding):
// 000 - Forward DATA2          (mov, loadi)
// 001 - Addition / Subtraction (add, sub, beq, bne)
// 010 - Bitwise AND            (and)
// 011 - Bitwise OR             (or)
// 100 - Multiply               (mult)               [Lab 4.5]
// 101 - Shift / Rotate         (sll, srl, sra, ror) [Lab 4.5]
//
// Unused SELECT values are handled safely
// by sending 0 to the output.

// New output for Lab 4:

//   ZERO    is 1 when the subtraction result is all-zero,
//           used by the beq instruction to decide whether to branch.

// New auxiliary control signals for Lab 4.5:
//   SHIFT_DIR  0 = shift left, 1 = shift right
//   ARITH      0 = logical shift, 1 = arithmetic shift right (sra)
//   ROTATE     0 = shift, 1 = rotate right (ror)
// These are generated by the control unit.

// Timing note:

// All functional units use a registered intermediate result (combinational
// logic in always @(*)) and expose their delay on a continuous assign wire.

// This prevents Verilog's inertial-delay cancellation that occurs when
// #N is placed inside always @(*) blocks and inputs change multiple times
// within the same N-unit window.  

// The pattern is:
//   always @(*) begin  <combinational logic, no delay>  end
//   assign #N RESULT = internal_wire;
// This mirrors the lab's timing model exactly.

`timescale 1ns/100ps


// Forward Unit
// RESULT = DATA2
// Delay = 1 time unit

module forward_unit(DATA2, RESULT);

    input  [7:0] DATA2;
    output [7:0] RESULT;

    // Combinational pass-through; delay on the output wire
    assign #1 RESULT = DATA2;

endmodule


// Add Unit
// RESULT = DATA1 + DATA2
// Delay = 2 time units

module add_unit(DATA1, DATA2, RESULT);

    input  [7:0] DATA1, DATA2;
    output [7:0] RESULT;

    // Combinational addition; delay on the output wire
    assign #2 RESULT = DATA1 + DATA2;

endmodule


// AND Unit
// RESULT = DATA1 & DATA2
// Delay = 1 time unit

module and_unit(DATA1, DATA2, RESULT);

    input  [7:0] DATA1, DATA2;
    output [7:0] RESULT;

    // Combinational AND; delay on the output wire
    assign #1 RESULT = DATA1 & DATA2;

endmodule


// OR Unit
// RESULT = DATA1 | DATA2
// Delay = 1 time unit

module or_unit(DATA1, DATA2, RESULT);

    input  [7:0] DATA1, DATA2;
    output [7:0] RESULT;

    // Combinational OR; delay on the output wire
    assign #1 RESULT = DATA1 | DATA2;

endmodule


// Lab 4_5 New Functional Units

// Multiply Unit  [Lab 4_5]
// RESULT = DATA1 * DATA2  (lower 8 bits)
// Implemented using a shift-and-add loop (no * operator).
// Latency: #2 time units, modelled on the output wire (not inside always @(*)).
// Delay = 2 time units

module mult_unit(DATA1, DATA2, RESULT);

    input  [7:0] DATA1, DATA2;
    output [7:0] RESULT;

    // Combinational shift-and-add; result is ready on mult_comb immediately,
    // then the #2 transport delay is added on the output wire.
    reg  [7:0] mult_comb;
    integer i;

    always @(*)
    begin
        mult_comb = 8'b00000000;
        // Shift-and-add: for each bit of the multiplier that is 1,
        // add the shifted multiplicand to the running partial sum.
        for (i = 0; i < 8; i = i + 1)
        begin
            if (DATA2[i] == 1'b1)
                mult_comb = mult_comb + (DATA1 << i);
        end
    end

    // Transport delay on the output wire
    assign #2 RESULT = mult_comb;

endmodule


// Barrel Shift / Rotate Unit  [Lab 4_5]
// Handles sll, srl, sra, and ror through a single module.

// DATA1       = value to shift/rotate
// DATA2[2:0]  = shift amount (0-7)
// SHIFT_DIR   = 0 (left), 1 (right)
// ARITH       = 0 (logical), 1 (arithmetic - fill with sign bit for right shift)
// ROTATE      = 0 (shift), 1 = rotate right

// New auxiliary control signals for Lab 4_5:
//   SHIFT_DIR  0 = shift left, 1 = shift right
//   ARITH      0 = logical shift, 1 = arithmetic shift right (sra)
//   ROTATE     0 = shift, 1 = rotate right (ror)
// These are generated by the control unit.

// Implementation: iterative single-bit shift/rotate repeated DATA2[2:0] times.
// Latency modelled on the output wire.
// Delay = 2 time units

module barrel_unit(DATA1, DATA2, SHIFT_DIR, ARITH, ROTATE, RESULT);

    input  [7:0] DATA1;
    input  [7:0] DATA2;    // shift amount in bits [2:0]
    input        SHIFT_DIR;
    input        ARITH;
    input        ROTATE;
    output [7:0] RESULT;

    reg [7:0] barrel_comb;
    reg       fill_bit;    // bit shifted in from left (arithmetic right shift)
    reg       msb;         // original sign bit, captured once
    integer   j;

    always @(*)
    begin
        barrel_comb = DATA1;
        msb         = DATA1[7];   // sign bit for arithmetic right shift

        // Repeat the one-bit shift/rotate DATA2[2:0] times
        for (j = 0; j < DATA2[2:0]; j = j + 1)
        begin

            if (ROTATE)
            begin
                // Rotate right: LSB wraps to MSB position
                barrel_comb = {barrel_comb[0], barrel_comb[7:1]};
            end
            else if (SHIFT_DIR == 1'b1)
            begin
                // Shift right
                // Arithmetic: fill from MSB (sign extension)
                // Logical:    fill with 0
                fill_bit    = (ARITH) ? msb : 1'b0;
                barrel_comb = {fill_bit, barrel_comb[7:1]};
            end
            else
            begin
                // Shift left (logical only): fill LSB with 0
                barrel_comb = {barrel_comb[6:0], 1'b0};
            end

        end
    end

    // Transport delay on the output wire
    assign #2 RESULT = barrel_comb;

endmodule


// Main ALU Module
// New port: ZERO - HIGH (ZERO = 1) when the result of a subtract is 0.
// The ZERO flag is used by beq to decide whether to take the branch.
// Lab 4_5: ZERO is also used by bne (branch if NOT zero).
//
// New auxiliary ports for Lab 4_5 shift/rotate control:
//   SHIFT_DIR  - forwarded straight to barrel_unit
//   ARITH      - forwarded straight to barrel_unit
//   ROTATE     - forwarded straight to barrel_unit

module alu(DATA1, DATA2, RESULT, SELECT, ZERO, SHIFT_DIR, ARITH, ROTATE);

    input  [7:0] DATA1, DATA2;
    input  [2:0] SELECT;

    // Lab 4_5 auxiliary control inputs (driven by control unit)
    input        SHIFT_DIR;
    input        ARITH;
    input        ROTATE;

    output [7:0] RESULT;

    // ZERO is 1 when RESULT == 0, used exclusively by beq / bne.
    output ZERO;
    assign ZERO = (RESULT == 8'b00000000) ? 1'b1 : 1'b0;

    // wires to get outputs from each unit
    wire [7:0] forward_result;
    wire [7:0] add_result;
    wire [7:0] and_result;
    wire [7:0] or_result;
    wire [7:0] mult_result;     // Lab 4.5
    wire [7:0] barrel_result;   // Lab 4.5 (sll / srl / sra / ror)


    // Unit Instantiations
    forward_unit f1  (DATA2, forward_result);
    add_unit     a1  (DATA1, DATA2, add_result);
    and_unit     and1(DATA1, DATA2, and_result);
    or_unit      o1  (DATA1, DATA2, or_result);

    // Lab 4_5 units
    mult_unit   mu (DATA1, DATA2, mult_result);
    barrel_unit bu (DATA1, DATA2, SHIFT_DIR, ARITH, ROTATE, barrel_result);


    // Result mux: zero-delay continuous assign so no extra delay is stacked
    // on top of the sub-unit propagation delays.
    // SELECT is stable 1 time-unit after OPCODE (decode delay),
    // well before sub-unit outputs settle at +2 time-units.
    assign RESULT = (SELECT == 3'b000) ? forward_result :
                    (SELECT == 3'b001) ? add_result     :
                    (SELECT == 3'b010) ? and_result      :
                    (SELECT == 3'b011) ? or_result       :
                    (SELECT == 3'b100) ? mult_result     :
                    (SELECT == 3'b101) ? barrel_result   :
                    8'b00000000;

endmodule
